# Generated by Django 5.2.5 on 2025-08-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tradicional', 'Sabores Tradicionais'), ('acompanhamento', 'Acompanhamentos'), ('especial', 'Sabores Especiais'), ('doce', 'Sabores Doces'), ('bebida', 'Bebidas')], default='tradicional', max_length=20),
        ),
    ]
